version = 0.1

[default.deploy.parameters]
stack_name = "hooray-staging"
region = "us-west-2"
profile = "hooray-staging"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = "Environment=staging SqsVisibilityTimeoutSeconds=60 SqsMaxReceiveCount=4 EnableEcsWorker=false"
