//! Idempotency service — prevents duplicate webhook events from being stored
//! and delivered more than once within the 24-hour idempotency window.
//!
//! ## How it works
//!
//! When a new `POST /webhooks/receive` request arrives, the handler calls
//! [`check_and_record`].  That function attempts a **conditional DynamoDB
//! `PutItem`** with `attribute_not_exists(pk)`.
//!
//! - If the item **did not exist** → write succeeds, the caller may proceed to
//!   create the event and enqueue it.
//! - If the item **already exists** (same `idempotency_key` seen within 24 h)
//!   → DynamoDB raises `ConditionalCheckFailedException`; the caller returns
//!   the previously assigned `event_id` with HTTP 200 (duplicate).
//!
//! Records expire automatically via the `ttl` attribute (DynamoDB TTL enabled
//! on the `webhook_idempotency` table).

use aws_sdk_dynamodb::Client as DynamoClient;
use aws_sdk_dynamodb::error::SdkError;
use aws_sdk_dynamodb::operation::put_item::PutItemError;
use aws_sdk_dynamodb::types::AttributeValue;
use serde_dynamo::aws_sdk_dynamodb_1::from_item;
use tracing::{debug, info, warn};

use crate::model::{IdempotencyRecord, IngestionError};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Outcome of an idempotency check.
#[derive(Debug)]
pub enum IdempotencyOutcome {
    /// First time this key is seen — the caller should proceed with event
    /// creation.  The `event_id` was pre-generated by the caller and written
    /// into the record.
    New,
    /// Key was seen within the 24-hour window.  Returns the `event_id` that
    /// was assigned when the request was first processed.
    Duplicate { event_id: String },
}

/// Attempt to atomically record an idempotency key.
///
/// # Arguments
/// - `client`           — DynamoDB client
/// - `table`            — name of the idempotency table
/// - `idempotency_key`  — caller-supplied dedup token
/// - `event_id`         — the event ID pre-generated for this request
/// - `created_at`       — Unix seconds; `ttl` is set to `created_at + 86_400`
///
/// # Returns
/// - `Ok(IdempotencyOutcome::New)`               — proceed with event creation
/// - `Ok(IdempotencyOutcome::Duplicate { .. })`  — return existing event_id
/// - `Err(IngestionError::DynamoDb)`             — unexpected infrastructure error
pub async fn check_and_record(
    client: &DynamoClient,
    table: &str,
    idempotency_key: &str,
    event_id: &str,
    created_at: i64,
) -> Result<IdempotencyOutcome, IngestionError> {
    // Validate created_at is within a reasonable Unix timestamp range
    // (between 2000-01-01 and 2100-01-01) to avoid invalid TTLs.
    const MIN_CREATED_AT: i64 = 946_684_800;  // 2000-01-01T00:00:00Z
    const MAX_CREATED_AT: i64 = 4_102_444_800; // 2100-01-01T00:00:00Z
    if created_at < MIN_CREATED_AT || created_at > MAX_CREATED_AT {
        return Err(IngestionError::DynamoDb(
            "invalid created_at timestamp for idempotency record".to_string(),
        ));
    }

    // Use checked_add to prevent overflow when computing the TTL.
    let ttl = created_at.checked_add(86_400).ok_or_else(|| {
        IngestionError::DynamoDb(
            "overflow when computing TTL for idempotency record".to_string(),
        )
    })?;

    let record = IdempotencyRecord {
        pk: IdempotencyRecord::pk_for(idempotency_key),
        event_id: event_id.to_string(),
        created_at,
        ttl,
    };

    let item = serde_dynamo::aws_sdk_dynamodb_1::to_item(&record)
        .map_err(|e| IngestionError::Serialization(e.to_string()))?;

    debug!(
        idempotency_key,
        event_id, "attempting conditional idempotency write"
    );

    let result = client
        .put_item()
        .table_name(table)
        .set_item(Some(item))
        // Only succeed if no item with this PK exists yet.
        .condition_expression("attribute_not_exists(pk)")
        .send()
        .await;

    match result {
        Ok(_) => {
            info!(idempotency_key, event_id, "idempotency key recorded — new event");
            Ok(IdempotencyOutcome::New)
        }
        Err(ref e) if is_conditional_check_failed(e) => {
            warn!(
                idempotency_key,
                "duplicate idempotency key detected — fetching existing event_id"
            );
            let existing_event_id =
                get_existing_event_id(client, table, idempotency_key).await?;
            Ok(IdempotencyOutcome::Duplicate {
                event_id: existing_event_id,
            })
        }
        Err(e) => Err(IngestionError::DynamoDb(e.to_string())),
    }
}

/// Retrieve the `event_id` already stored for a given `idempotency_key`.
///
/// Called only on the duplicate path — after a `ConditionalCheckFailedException`
/// confirms the record exists.
pub async fn get_existing_event_id(
    client: &DynamoClient,
    table: &str,
    idempotency_key: &str,
) -> Result<String, IngestionError> {
    let pk = IdempotencyRecord::pk_for(idempotency_key);

    let resp = client
        .get_item()
        .table_name(table)
        .key("pk", AttributeValue::S(pk.clone()))
        .send()
        .await
        .map_err(|e| IngestionError::DynamoDb(e.to_string()))?;

    let item = resp.item.ok_or_else(|| IngestionError::ItemNotFound {
        entity: "IdempotencyRecord",
        key: pk.clone(),
    })?;

    let record: IdempotencyRecord = from_item(item)?;

    debug!(
        idempotency_key,
        existing_event_id = %record.event_id,
        "retrieved existing event_id for duplicate key"
    );

    Ok(record.event_id)
}

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/// Returns `true` when a DynamoDB `PutItem` error is a
/// `ConditionalCheckFailedException` — indicating the item already exists.
pub fn is_conditional_check_failed(
    err: &SdkError<PutItemError>,
) -> bool {
    matches!(
        err,
        SdkError::ServiceError(svc) if matches!(
            svc.err(),
            PutItemError::ConditionalCheckFailedException(_)
        )
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // --- event_id format ---

    #[test]
    fn event_id_has_evt_prefix() {
        // nanoid-generated IDs must always carry the `evt_` prefix so that
        // downstream systems (worker, logs, dashboards) can recognize them.
        let event_id = format!("evt_{}", nanoid::nanoid!(21));
        assert!(
            event_id.starts_with("evt_"),
            "event_id must start with 'evt_' — got: {event_id}"
        );
    }

    #[test]
    fn event_id_minimum_length() {
        // `evt_` (4) + at least 8 random chars = 12 minimum.
        let event_id = format!("evt_{}", nanoid::nanoid!(21));
        assert!(
            event_id.len() >= 12,
            "event_id too short: {event_id}"
        );
    }

    #[test]
    fn idempotency_record_pk_format() {
        let pk = IdempotencyRecord::pk_for("req_abc123");
        assert_eq!(pk, "IDEM#req_abc123");
    }

    #[test]
    fn idempotency_record_ttl_is_24h_after_created_at() {
        let created_at = 1_707_840_000_i64;
        let record = IdempotencyRecord {
            pk: IdempotencyRecord::pk_for("req_ttl_test"),
            event_id: "evt_ttl_test".to_string(),
            created_at,
            ttl: created_at + 86_400,
        };
        assert_eq!(record.ttl - record.created_at, 86_400);
    }

    #[test]
    fn idempotency_record_serializes_for_dynamo() {
        // Ensures serde_dynamo can convert the struct without panicking.
        let record = IdempotencyRecord {
            pk: IdempotencyRecord::pk_for("req_serial_test"),
            event_id: "evt_serial_test".to_string(),
            created_at: 1_707_840_000,
            ttl: 1_707_840_000 + 86_400,
        };
        let item = serde_dynamo::aws_sdk_dynamodb_1::to_item(&record);
        assert!(item.is_ok(), "serialization should succeed: {:?}", item.err());
    }
}
